### PR TITLE
Cut release 0.3.0

### PR DESCRIPTION
**Pull request by matthiasr**
@sdurrheimer sorry for the stupid Q, but after this I just tag/release and that's it, right?

### CODE REVIEW

**Comment by matthiasr** [comment]
cc @brian-brazil – just trying to make mailing list users happy :)

**Comment by grobie** [comment]
You need to create a release before circleCI is done. If CircleCI sees a new tag it'll start the release process. At the end it'll try to upload all binaries to Github and append it to the release.

I prefer creating tags locally as that means I can sign them, alternatively you can create tag+release at once via the github UI.

**Comment by matthiasr** [comment]
Updated the changelog to mention that the new release process changes the tarball structure.

**Comment by sdurrheimer** [comment]
_summons @juliusv_

**Comment by brian-brazil** [comment]
:+1:

**Comment by matthiasr** [comment]
Lets see if I did this right …

**Comment by sdurrheimer** [comment]
Dammit, I should have seen this, we missed to update the VERSION file. 
The build [failed](https://circleci.com/gh/prometheus/collectd_exporter/8) during release upload because some tarballs already exists on the release. True, he upload them on the 0.2.0 release...

**Comment by matthiasr** [comment]
Ouch! I'll bump the version to 0.3.1 and try again.

**Comment by sdurrheimer** [comment]
no need to go 3.1 I think, we can just fix the file and redo the 0.3.0 tag

**Comment by matthiasr** [comment]
I don't like manipulating releases after they are cut – I'd rather just bump the patch version until we get it right. (which I just did because I hadn't seen your comment yet)

**Comment by sdurrheimer** [comment]
We have just cut it, so I don't see the problem, given that this 0.3.0 will be useless in the list (bad `collectd_exporter -version`, no tarballs).

**Comment by matthiasr** [comment]
Re-defining a tag is rewriting history, which I'd rather not do on a public repository/branch, no matter how useless the tag ends up being. I'm happy to delete the 0.3.0 release so we go from 0.2.0 to 0.3.1 right away, but as soon as 0.3.0 was out there, even for only 2 minutes, I'd like to keep it unchanged.

**Comment by discordianfish** [comment]
If it's not really released, I'm fine with changing it. Not that important though IMO.

**Pull request merged**
