### PR TITLE
Release 0.5.0

### PR DESCRIPTION
**Pull request by SuperQ**
* [CHANGE] Switch logging to go-kit (#85)

Signed-off-by: Ben Kochie <superq@gmail.com>

### CODE REVIEW

**Comment by SuperQ** [comment]
This also upgrades the vendoring, including the latest Go collectd library. Also a Go 1.7 -> 1.14 rebuild.

**Comment by roidelapluie** [comment]
Can we deprecate at the same time?

**Comment by juliusv** [comment]
Ah great that @SuperQ is already working on a release, thanks!

Yeah @roidelapluie, I would propose making this the last release of the collectd exporter and then marking it as deprecated at the top of the README.md (see https://groups.google.com/forum/#!topic/prometheus-users/scP-0JcEgtc for context), with a text like:

> **NOTE:** THIS EXPORTER HAS BEEN **DEPRECATED** IN FAVOR OF UPSTREAM PROMETHEUS SUPPORT IN COLLECTD: https://collectd.org/wiki/index.php/Plugin:Write_Prometheus.
>
> Please switch to the upstream Prometheus module for collectd and work with the authors there to add any missing functionality. We will not be accepting changes to this exporter anymore and will be removing the exporter repository in due time.

**Comment by juliusv** [comment]
And :+1: on this PR :)

**Comment by SuperQ** [comment]
I'd like to have a discussion about marking this deprecated. Maybe @octo is interested in weighing in on this.

I'd suggest opening a separate issue to discuss arching this project. For now, I'd like to cut a release as normal. We can add a deprecation notice afterwards.

**Comment by juliusv** [comment]
See my last reply on the thread I linked (I had screwed up the CC to list, so you'll only see @octo's reply quoted by me there). Basically:

> I'm not aware of anything that the collectd_exporter does that the
"write_prometheus" plugin doesn't support – and I'm happy to get the
plugin to feature parity if anything comes up.

So I think we can safely deprecate it.

**Pull request merged**
