### PR TITLE
Switch to promhttp handler and continue on error

### PR DESCRIPTION
**Pull request by vbatoufflet**
Hi all,

This PR follows a discussion started in #56 and use the new HTTP handler provided by the `promhttp` package along with the `promhttp.ContinueOnError` error handler to prevent inconsistent metrics from preventing the whole scraping.

Please let me know if this requests suits you or if I missed something here.

Regards.

### CODE REVIEW

**Comment by brian-brazil** [comment]
When cAdvisor did similar in https://github.com/google/cadvisor/pull/1679 it ended up making the scrape succeed, but instead started returning arbitrary subsets of the metrics.

**Comment by vbatoufflet** [comment]
Indeed, the metric not matching the stable label length criterion isn't sent anymore.

Wouldn't it be better that I make this behavior configurable via a command-line argument?

**Comment by brian-brazil** [comment]
I don't think it's a good idea to add a `--randomly-break` flag, the way to handle this is to fix the labels.

**Comment by vbatoufflet** [comment]
Ok I understand.

When you say fix the label. You mean in collectd_exporter or upstream in collectd?

**Comment by brian-brazil** [comment]
Wherever it needs to be fixed, I'm not too familiar with this part of collectd.

**Comment by vbatoufflet** [comment]
Ok, so I'll close this PR keeping the original issue regarding the incompatibility open.

**Comment by beorn7** [comment]
> Indeed, the metric not matching the stable label length criterion isn't sent anymore.

Yes, that's the idea behind the option. The client library is designed to never create invalid output, thus it can only fail completely or leave out the offending parts.

**Comment by vbatoufflet** [comment]
Indeed @beorn7, I implemented this change exactly for that purpose as I can't use the `collectd_exporter` at the moment with collectd instances exporting conntrack data.

I'll use my own version for tests waiting to find a proper fix that suits everyone to make the exporter compatible with collectd's way to export such metrics trough binary protocol.

**Comment by brian-brazil** [comment]
Have you considered using collectd's own Prometheus metrics output? It lacks this sanity checking.

**Comment by vbatoufflet** [comment]
I must admit that I wasn't aware of its existence. Thanks! I'll take a look at it.

**Pull request closed without merging**
