### PR TITLE
Implement support for collectd's binary network protocol.

### PR DESCRIPTION
**Pull request by octo**
Flag names emulate the config options of collectd's network plugin.

### CODE REVIEW

**Comment by juliusv** [comment]
:+1: Thanks! Let me know if you want to be the maintainer :)

**Comment by octo** [comment]
@juliusv I'm happy to take this on. I'm stretched a bit thin though, so it'd be great if I wasn't a SPoF for this …

**Comment by juliusv** [comment]
@octo Happy to do it together :) Should I add you to the maintainers list and keep myself in there as well?

**Comment by juliusv** [comment]
PR to update AUTHORS.md here: https://github.com/prometheus/collectd_exporter/pull/12

**Comment by octo** [comment]
@juliusv Sounds great, thank you! :)

**Pull request merged**
