### PR TITLE
Mark the collectd exporter as deprecated

### PR DESCRIPTION
**Pull request by juliusv**
Signed-off-by: Julius Volz <julius.volz@gmail.com>

Context: https://github.com/prometheus/collectd_exporter/pull/95#issuecomment-626669322

### CODE REVIEW

**Comment by juliusv** [comment]
@SuperQ

**Comment by kamilpoleszczuk** [comment]
Hi. Is it confirmed that repository will be removed? As per discussion [here](https://github.com/prometheus/collectd_exporter/issues/93) https support can be easily added to collectd_exporter (even by patching locally). Unfortunately TLS is not supported by write_prometheus plugin.

**Comment by juliusv** [comment]
@octo How is TLS usually addressed on the collectd side?

**Comment by obitech** [comment]
Hey, any background on why it's being deprecated?

**Comment by juliusv** [comment]
Ah sorry, I should have included more context in here as well, see https://github.com/prometheus/collectd_exporter/pull/95#issuecomment-626669322

**Comment by hasso** [comment]
Collectd_exporter had much (several times) better performance than collectd when we investigated about year ago or so. I might revisit it at some point, but I don't think that anything is really changed in this regard.

**Comment by SuperQ** [comment]
@hasso If you could provide some benchmarks and proof of this, it would make for a very good use case to keep this project going.

**Comment by matthiasr** [comment]
Rather than splitting the effort between two options, could it be invested
in making collectd faster?

**Review by SuperQ — APPROVED** [review]

**Comment by SuperQ** [comment]
@hasso Are you still using this exporter?

**Comment by hasso** [comment]
> @hasso Are you still using this exporter?

Yes, I do. And probably will continue to use in the near future.

**Comment by SuperQ** [comment]
@hasso Would you be willing to put in the time to become a maintainer?

**Comment by juliusv** [comment]
See also https://groups.google.com/g/prometheus-developers/c/FX4NjCckoa8

**Comment by hasso** [comment]
> @hasso Would you be willing to put in the time to become a maintainer?

Yes.

**Comment by SuperQ** [comment]
I think there's enough interest in this that we can keep maintaining this as-is.

**Pull request closed without merging**
