### PR TITLE
Integrate upstream API changes.

### PR DESCRIPTION
**Pull request by octo**
This fixes API breaking upstream changes, see collectd/go-collectd#21 for details.

This is basically a heads-up that should be merged when the upstream PR is merged – I'm happy to do that. The upstream changes have not yet been copied to `vendor/` – that should happen prior to actually merging this.

### CODE REVIEW

**Comment by juliusv** [comment]
Thanks! Hmm, the upstream change depends on Go 1.7, which is not even released yet (although it should be right around the corner). That's why the tests are failing.

Options for now are:

a) leave it broken until Go 1.7 in hopefully the next week or so, then change build/test files to require Go 1.7
b) vendor an old version of the upstream lib and keep the code as is otherwise

While we wouldn't want to require Go 1.7 for the Go client lib or the Prometheus server yet, it's probably fine for the collectd_exporter once Go 1.7 is out.

**Comment by octo** [comment]
Go 1.7 is available and collectd/go-collectd#21 has been merged (though not in that order ;).

I'll copy the required upstream version to `vendor/`, then this should be good to go.

**Comment by bensonk** [comment]
I am happy to have found this, as I tried to compile collectd_exporter today, found it didn't work, merged in this PR to my working copy, and now it works. So, hooray! Is now a good time to do the merge?

**Comment by octo** [comment]
Unfortunately I didn't find any instructions on how to update `vendor/`. @sdurrheimer, did you use *govendor* or something else?

**Comment by sdurrheimer** [comment]
@octo yes we do use `govendor` for all our golang components.

**Comment by juliusv** [comment]
Yes, good to merge once the vendored dependencies are updated!

**Comment by juliusv** [comment]
@octo Oh, forgot to mention that you'll also have to update all the build and CI files to use only Go 1.7 now:

https://github.com/prometheus/collectd_exporter/blob/master/.promu.yml#L1
https://github.com/prometheus/collectd_exporter/blob/master/circle.yml#L5
https://github.com/prometheus/collectd_exporter/blob/master/.travis.yml#L6-L7

**Comment by octo** [comment]
Alright, I think this is good to go from the code side. However, the CI setup has not yet been updated for Go 1.7, so once this is merged all CI jobs will start failing. :cry:

**Comment by octo** [comment]
@juliusv Thanks for the pointers, I'll give it a try.

**Comment by octo** [comment]
Alright, that was easier than expected. \o/

**Comment by juliusv** [comment]
Yay \o/ Thanks, merging.

**Pull request merged**
